import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header>
					{" "}
					<Navbar />
				</header>
				<main className="flex flex-col mx-auto w-5/6 max-h-full">{children}</main>
			</body>
		</html>
	)
}
